services:
  runtime:
    image: boomi/atom:release
    container_name: ${NODE_NAME}
    user: "1000:1000"
    restart: unless-stopped
    hostname: ${NODE_NAME}
    environment:
      BOOMI_ACCOUNTID: ${BOOMI_ACCOUNTID}
      BOOMI_ENVIRONMENTID: ${BOOMI_ENVIRONMENTID}
      INSTALL_TOKEN: ${INSTALL_TOKEN}
      BOOMI_ATOMNAME: ${ATOM_NAME}
      ATOM_LOCALHOSTID: ${NODE_NAME}
      LOCAL_PATH: "/opt/boomi"
      JAVA_OPTS: "-Xms2048m -Xmx4096m -Dboomi.containerized=true"
    ports:
      - "9090:9090"
      - "7800-7900:7800-7900"
      - "61717:61717"
    volumes:
      - ./boomi/local:/opt/boomi
      - ./boomi/share:/mnt/boomi
    networks:
      - otel_network

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    environment:
      HOSTNAME: alloy
      OBS_HOST: 172.31.19.58
    volumes:
      - ./alloy.yaml:/etc/alloy/config.alloy:ro
      - alloy_data:/var/lib/alloy/data
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    networks:
      - otel_network
    ports:
      - "12345:12345"

volumes:
  alloy_data:

networks:
  otel_network: