services:
  # Boomi Runtime
  runtime:
    image: boomi/atom:release
    container_name: ${LOCALHOST_ID}
    restart: unless-stopped
    hostname: ${LOCALHOST_ID}
    environment:
      BOOMI_ACCOUNTID: ${BOOMI_ACCOUNTID}
      BOOMI_ENVIRONMENTID: ${BOOMI_ENVIRONMENTID}
      INSTALL_TOKEN: ${INSTALL_TOKEN}
      BOOMI_ATOMNAME: ${ATOM_NAME}
      ATOM_LOCALHOSTID: ${LOCALHOST_ID}
      ATOM_VMOPTIONS_OVERRIDES: "-Xms1g|-Xmx2g|-javaagent:/mnt/boomi/pyroscope/agent-2.1.2.jar"
      PYROSCOPE_APPLICATION_NAME: boomi
      PYROSCOPE_SERVER_ADDRESS: http://alloy:4040
    ports:
      - "9090:9090"
    volumes:
      - ./boomi:/mnt/boomi
    networks:
      - boomi

  # Alloy - Sink for Boomi OpenTelemetry data
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    environment:
      HOSTNAME: alloy
      TEMPO_HOSTNAME: ${OBSERVABILITY_HOSTNAME}
      LOKI_HOSTNAME: ${OBSERVABILITY_HOSTNAME}
      PROMETHEUS_HOSTNAME: ${OBSERVABILITY_HOSTNAME}
      PYROSCOPE_HOSTNAME: ${OBSERVABILITY_HOSTNAME}
    ports:
      - "12345:12345"
    extra_hosts:
      # This line is only for the demo install to resolve observability to the docker host
      - "observability:host-gateway"  
    volumes:
      - ./alloy/alloy.yml:/etc/alloy/config.alloy:ro
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    networks:
      - boomi


networks:
  boomi:
    driver: bridge